version: "2"
services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    networks:
      - hadoop_net
    # volumes:
    #   - ./namenode:/tmp/hadoop-root/dfs/name
  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    networks:
      - hadoop_net
    # volumes:
    #   - ./datanode:/tmp/hadoop-hadoop/dfs/data
  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      - hadoop_net
  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    networks:
      - hadoop_net

  spark-master:
    image: bitnami/spark:latest
    hostname: spark-master
    command: ["spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - 8080:8080 # Interface Web Spark Master
      - 7077:7077 # Port Spark Master
      - 8051:8051 # Dash app
    env_file:
      - ./config
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - HADOOP_CONF_DIR=/opt/bitnami/hadoop/conf
    networks:
      - hadoop_net
    depends_on:
      - namenode
      - resourcemanager

  spark-worker:
    image: bitnami/spark:latest # Exemple d'une image Spark préexistante
    command:
      [
        "spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077",
      ]
    env_file:
      - ./config
    environment:
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - HADOOP_CONF_DIR=/opt/bitnami/hadoop/conf
    networks:
      - hadoop_net
    depends_on:
      - spark-master

networks:
  hadoop_net:
    driver: bridge
